### ISSUE TITLE
/rpgc menu error

### ISSUE THREAD

**Issue by benr233** [spigot-gillesm/RPGChest-Premium#24] opened 2020-04-10 16:26 UTC
[00:20:35 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'rpgc menu' in me.gilles_m.RPGChestPremium.goto. .Aux(rpgchest)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:742) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1821) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1629) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.STAINED_GLASS_PANE
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_161]
        at org.bukkit.Material.valueOf(Material.java:84) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        at me.gilles_m.RPGChestPremium.goto. .coM1.do(SourceFile:99) ~[?:?]
        at me.gilles_m.RPGChestPremium.core_lib.guilib.menus.StandardMenu.<init>(SourceFile:32) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .com9.do(SourceFile:14) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .AuX.do(SourceFile:27) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .NUl.for(SourceFile:79) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .nUl.do(SourceFile:79) ~[?:?]
        at me.gilles_m.RPGChestPremium.goto. .nUl.execute(SourceFile:60) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[Paper-1.15.2-b121.jar:git-Paper-120]
        ... 16 more

**Comment by spigot-gillesm** [comment] 2020-04-11 12:24
Hello

On what version of the game is the server running? If you had a previous build before using this one, are you sure you have correctly updated the plugin? (only the latest RPGChest file is present in you plugins folder)

Sorry for the inconvenience

**Comment by benr233** [comment] 2020-04-11 12:27
The server version is 1.15.2 paper, and the plug-in is the latest version

**Comment by spigot-gillesm** [comment] 2020-04-11 12:33
Alright I'll look into it as soon as I can!

**Comment by benr233** [comment] 2020-04-11 12:35
thanks :)

**Comment by spigot-gillesm** [comment] 2020-04-11 18:23
Okay so with what I could understand from the stack trace you gave me it seems that RPGChest Library is running with its features adapted for versions of Minecraft below 1.13. This is why the plugin is trying to use org.bukkit.Material.STAINED_GLASS_PANE but this material name no longer exists.

Another user of mine reported me the same error (the library running for 1.12 instead of 1.15). He fixed the problem by making a complete reinstallation of RPGChest premium (double check any other RPGChest file and make sure only the latest is present in /plugins). So try to do that: completely shut down the server, remove all the RPGChest files (you can keep the /RPGChest folder of course) put RPGChest v2.6.5.0 in /plugins and start your server once it's done. Do not use Plugman or any other similar stuff!

If the problem persists, I'll send you a build with debugging entries to find the exact source of problems

**Comment by benr233** [comment] 2020-04-11 23:01
The server installed the RPGC for the first time and the plug-in was not working properly.

**Comment by benr233** [comment] 2020-04-11 23:05
You can try to get the RPGC to work on 1.15.2 paper, and you will find that there are a lot of null errors

**Comment by spigot-gillesm** [comment] 2020-04-11 23:26
I tried again using the **very latest paper spigot build** (#172) and the RPGChest build downloaded from the spigot page but I couldn't manage to reproduce your bug:

![image](https://user-images.githubusercontent.com/54368573/79056957-22bf0180-7c5c-11ea-827d-93d17a14ecfa.png)

I'll send you a special build tomorrow to get additional informations about what is causing these problems. Could you contact me on Discord or give me your Discord tag? (if you have a Discord account)

**Comment by benr233** [comment] 2020-04-11 23:29
Sorry, I'm not good at using discord. Do you have any other ways to contact me? Or I offer you logs

**Comment by spigot-gillesm** [comment] 2020-04-11 23:39
No problem you can contact me via direct message over Spigot so we don't bother anyone (and don't flood the issue sections with screenshots). I'll have to go now as it's very late here

Sorry again for the troubles, I hope we'll be able to work it out quickly!

**Comment by spigot-gillesm** [comment] 2020-04-12 18:07
Since it has been worked out I'm closing the ticket. Feel free to re open it if the issue comes back

**Closed as completed by spigot-gillesm** 2020-04-12 18:07 UTC
Labels: Issue: bug
