### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by LucidAPs** [spigot-gillesm/RPGChest-Premium#3] opened 2019-12-11 14:06 UTC
Reload command doesn't work and returns an error
https://pastebin.com/brxAmgjk
minecraft 1.14.4 paper build 235

**Comment by spigot-gillesm** [comment] 2019-12-12 10:36
Hello and sorry for the inconvenience. I’ll try to fix your issue today but before trying anything I highly recommend you to check there are no mistakes or typo in your config files as issues coming from reloading are often caused by error while enabling features or items configured with the files (especially if the command used to work)

**Comment by LucidAPs** [comment] 2019-12-12 10:44
Yeah i thought about that aswell so i double checked the yml's and it still had a problem, infact the problem persisted with the default ymls and when only making changes through the gui menu and not touching the files. 
Also the permission nodes don't auto complete when working with /lp editor (luckperms) which is unusual for most plugins.

**Comment by spigot-gillesm** [comment] 2019-12-12 12:08
Alright I’ll take a look and tell you what can be done to fix the issue or push an update to fix it if it’s needed

**Comment by spigot-gillesm** [comment] 2019-12-13 09:29
Hello again

So I took a look at your issue and it seems the problem comes from an event called when an RPGChest is closed, saying that the player data (the thing used to know how many times a player has opened containers) is causing a bug. I used the exact same RPGChest-1.9.0.0 file to test the reload command (and opening/closing of containers) to see if I could re-produce the bug but I couldn't. There were no errors in the console.

So my guess is the issue doesn't come from the reload but from a mistake in the player_data file. Could you check the content of the file?
If the issue persists, please contact me on Discord: Gilles_M#8127 (if you don't have Discord, we can keep using this thread but it's less convenient as we might need to chat to solve this problem)

**Comment by spigot-gillesm** [comment] 2020-02-15 13:07
As the ticket is old now and no other issue has been reported, I'm closing the ticket. Feel free to open a new one if needed

**Closed as completed by spigot-gillesm** 2020-02-15 13:07 UTC
